version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shilkinkaya-frontend
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      # Mount for development hot reload (comment out in production)
      - ./src:/app/src:ro
      - ./public:/app/public:ro

  # Development service with hot-reloading enabled
  dev:
    image: node:23-alpine
    container_name: shilkinkaya-frontend-dev
    working_dir: /app
    command: sh -c "yarn install && yarn dev"
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
    tty: true

networks:
  default:
    name: shilkinkaya-network